### ISSUE TITLE
Del

### ISSUE THREAD

**Issue by ftk** [itmoasm2015/Homework3#11]
2538/fotyev
Работает на 64-битных Windows и Linux

**Comment by imihajlow** [comment]
Нужно сохранять R15.

**Comment by ftk** [comment]
Исправлено

**Comment by imihajlow** [comment]
`biFromString` не должна допускать строку "-".

**Comment by ftk** [comment]
Fixed

**Comment by imihajlow** [comment]
Код 8, комментарии 6, бонус 3 за Windows и 2 за модульность.
