### ISSUE TITLE
Збань Илья, 2539

### ISSUE THREAD

**Issue by izban** [itmoasm2015/Homework3#14]
Без деления.
UPD: Уже и с делением.

**Comment by imihajlow** [comment]
```
test.cpp:3:19: fatal error: gmpxx.h: No such file or directory
```

Если ваш Makefile по умолчанию делает что-то кроме требуемой библиотеки, он не должен падать.

**Comment by izban** [comment]
Исправил

**Comment by imihajlow** [comment]
Число не равно само себе (biCmp).

**Comment by izban** [comment]
Исправил

**Comment by imihajlow** [comment]
```
test: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
```

**Comment by izban** [comment]
Исправил

**Comment by imihajlow** [comment]
2^1024 + (-(2^1024 - 1)) ≠ 1

**Comment by izban** [comment]
Исправил

**Comment by imihajlow** [comment]
Строка "-" не должна допускаться функцией `biFromString`.

**Comment by izban** [comment]
Исправил

**Comment by izban** [comment]
И добавил деление.

**Comment by imihajlow** [comment]
Стек перед вызовом внешних функций должен быть выровнен на 16 байт (перед вызовом `malloc` у вас стек не выровнен). Проверьте все вызовы.

**Comment by izban** [comment]
Исправил стек перед вызовами всех внешних функций.
Перед вызовом  своих функций не обязательно выравнивать стек, если они этого не требуют?

**Comment by imihajlow** [comment]
Да, необязательно. Внутри можно делать что угодно, а при работе с внешними функциями нужно соответствовать конвенции вызова.

**Comment by imihajlow** [comment]
Код 8, комментарии 7.
