### ISSUE TITLE
Patrikeev Sergey 2538

### ISSUE THREAD

**Issue by serejke** [itmoasm2015/Homework3#15]
Подскажите, как узнать, будет ли переполнение (overflow), если поделить беззнаково (RDX:RAX) на 64-битный регистр, вылетает floating point exception, можно ли его как-то ловить или предсказывать?

**Comment by imihajlow** [comment]
Исключение не перехватить никак, его обрабатывает операционная система.
Проверить можно так: исключение возникнет, если частное не поместится в 64 бита. Минимальное делимое, которое при данном делителе (d) вызовет переполнение, будет равно `d * 2^64`. Значит, переполнение будет только в том случае, если старшие 64 бита делимого (rdx) больше или равны делителю.
