### ISSUE TITLE
Патрикеев Сергей 2538

### ISSUE THREAD

**Issue by serejke** [itmoasm2015/Homework3#16]
Есть деление и вывод в строку
Система счисления 2^64
Относительно быстрое деление, за 3 операции считает очередную цифру

**Comment by imihajlow** [comment]
Код 8, комментарии 7. Бонус 2 (хорошо протестировано).

**Comment by imihajlow** [comment]
cheat_factor = 0.5 (такой же код, как у Качальского).

**Comment by imihajlow** [comment]
cheat_factor = 1.
