### ISSUE TITLE
Марковников Никита, гр. 2537

### ISSUE THREAD

**Issue by mikita95** [itmoasm2015/Homework3#17]
2537/Markovnikov

**Comment by mikita95** [comment]
Без деления

**Comment by imihajlow** [comment]
Стек перед вызовом внешних функций должен быть выровнен на 16 байт (перед вызовом `malloc` у вас стек не выровнен). Проверьте все вызовы.

**Comment by mikita95** [comment]
Исправил

**Comment by imihajlow** [comment]
Нет. Всё еще не выровнено. Скорей всего, в `biFromStr`.

**Comment by mikita95** [comment]
Надеюсь теперь правильно. Исправил)

**Comment by imihajlow** [comment]
В `Makefile` ошибка, не указана зависимость для `libhw.o`, и поэтому библиотека не пересобирается после изменения файла.

**Comment by mikita95** [comment]
Добавил

**Comment by imihajlow** [comment]
А всё равно не выровнено, теперь в другом месте. Воспользуйтесь инструментом, который лежит в папке fcheck.

**Comment by mikita95** [comment]
Теперь не ругается

**Comment by imihajlow** [comment]
RBX надо сохранять.

**Comment by mikita95** [comment]
Исправлено.

**Comment by imihajlow** [comment]
Строка 285, например:

```
and rsp, 0xFFFFFFF0
```

Представьте, что будет, если rsp окажется больше 0x100000000.

**Comment by mikita95** [comment]
Исправил

**Comment by imihajlow** [comment]
Код 7, комментарии 5.

А почему вы выбрали основание 10^9 и 32 бита, а не 10^19 и 64?

**Comment by mikita95** [comment]
Не знаю. Я как-то даже не подумал об этом)
