### ISSUE TITLE
Векторные операции

### ISSUE THREAD

**Issue by AVBelyy** [itmoasm2015/Homework3#2]
SSE2 и SSE3 поддерживают "вертикальное" сложение запакованных 32/64-битных integer'ов (инструкции PADDD/PADDQ), но игнорируют флаг переноса, если он возникнет:

```
Note that the PADDB, PADDW, and PADDD instructions can operate on either unsigned
or signed (two's complement notation) packed integers; however, it does not set bits in
the EFLAGS register to indicate overflow and/or a carry. To prevent undetected overflow
conditions, software must control the ranges of values operated on.
```

Это очень нежелательно, если хранить числа в виде массива поразрядных dword'ов/qword'ов.

Сложение очень важно, потому что вычитание – это тоже сложение, а умножение – это n сложений. И если не получится реализовать сложение, чувствую, что и с остальным не получится.

Подскажите, как организовать хранение длинных чисел или какую иную инструкцию для сложения использовать, чтобы воспользоваться преимуществами векторизации (кроме огромных XMM/YMM-регистров) в данном задании?

**Comment by imihajlow** [comment]
Да, действительно, одно сложение проще сделать на базовом наборе инструкций (и работать даже будет быстрее). А вот в умножении уже можно применить векторную арифметику, чтобы эффективнее сложить более двух чисел. Почитайте: http://stackoverflow.com/questions/27923192/practical-bignum-avx-sse-possible
