### ISSUE TITLE
Пересадин Илья, 2539

### ISSUE THREAD

**Issue by pva701** [itmoasm2015/Homework3#20]
Нет деления

**Comment by imihajlow** [comment]
Нет заглушки для `biDivRem`.

**Comment by pva701** [comment]
Добавил

**Comment by imihajlow** [comment]
Код 8, комментарии 7, бонус 2 (хорошо протестировано).

А почему 10^8, а не 10^9 или не 10^19 (64 бита?

**Comment by pva701** [comment]
На всякий случай, чтобы ничего нигде не переполнилось при сложении или еще где.
