### ISSUE TITLE
Моклев Вячеслав, 2539

### ISSUE THREAD

**Issue by slavam2605** [itmoasm2015/Homework3#21]
Реализованы все операции.
Деление реализовано так, что на вычисление каждой 64-битной цифры уходит в среднем 1, но не более 3 операций (долгих операций, а именно 1 умножение, 1 сдвиг и 1 вычитание)
Код качественно задокументирован с использованием аналога javadoc
У полей и некоторых методов есть атрибут комментарием @contract -- такие операции
требуют выполнения контракта при их выполнении, а поля -- гарантируют такие свойства.
В коде явно указаны и прокомментированы все места, где это свойство используется или поддерживается. Таким образом, в комментариях содержится часть доказательства того, что все операции вычисляют именно то, что заявлено.
Кстати, подробное доказательство выявило немало ошибок)

**Comment by imihajlow** [comment]
Код 8, комментарии 7, бонус 2 (хорошо протестировано).
