### ISSUE TITLE
Кузнецов Николай, 2539

### ISSUE THREAD

**Issue by knah** [itmoasm2015/Homework3#23]
Длинная арифметика, с переводом в строку и делением.
Деление использует бинарный поиск по ответу и работает за O(mn^2), где m - размер делителя, n - размер делимого. Умножение работает за O(nm), перевод в строку за O(n^2), из строки - тоже O(n^2), сложение, вычитание, сравнение - за O(n + m), biSign - за O(1).

**Comment by imihajlow** [comment]
Код 8, комментарии 7, бонус 2 (хорошо протестировано), 1 (указаны сложности алгоритмов).
