### ISSUE TITLE
Филиппов Дмитрий, 2539

### ISSUE THREAD

**Issue by DimaPhil** [itmoasm2015/Homework3#24]
Все, вместе с biToString, biDivRem

**Comment by imihajlow** [comment]
```
test.cpp:3:19: fatal error: gmpxx.h: No such file or directory
```

**Comment by DimaPhil** [comment]
Убрал gmp

2015-05-09 9:14 GMT+03:00 Ivan Mikhaylov notifications@github.com:

**Comment by imihajlow** [comment]
Код 8, комментарии 7, бонус 2 (хорошо протестировано).
