### ISSUE TITLE
Качальский Илья, 2536

### ISSUE THREAD

**Issue by IlyaHalsky** [itmoasm2015/Homework3#26]
2536/Kachalskiy

**Comment by imihajlow** [comment]
```
'../Homework3/2536/Kachalskiy/libhw.a': No such file
```

**Comment by IlyaHalsky** [comment]
Так должно стать лучше

**Comment by imihajlow** [comment]
Бинарник в репозитории появился, лучше не стало.

**Comment by IlyaHalsky** [comment]
Очень странно,в Makefile этого нет, возможно оно проползло из предыдущих версий.

**Comment by imihajlow** [comment]
Что проползло? Библиотека должна называться `libhw.a`, а не `biginteger.a`.

**Comment by IlyaHalsky** [comment]
Извиняюсь, проспал в условии название.

**Comment by imihajlow** [comment]
Код 8, комментарии 7, бонус 1 (хорошо протестировано, -1 за название библиотеки).

**Comment by imihajlow** [comment]
cheat_factor = 0.5 (такой же код, как у Патрикеева).

**Comment by AVBelyy** [comment]
Планируется ли запуск алгоритма по поиску несправедливости для всех предыдущих домашних заданий?

**Comment by imihajlow** [comment]
Спасибо за признание, cheat_factor = 0.

**Comment by imihajlow** [comment]
@AVBelyy Знаете какие-то инструменты для этого или придется руками скрипт писать?

**Comment by AVBelyy** [comment]
@imikhajlow Средств не знаю. И, наверное, доказывать свою честность в O(n^2) случаях будет менее приятно, чем в единичных. Так что идея не очень хорошая.
