### ISSUE TITLE
Немченко Евгений, 2538

### ISSUE THREAD

**Issue by eugene536** [itmoasm2015/Homework3#28]
2538/Nemchenko
biToString + biDivRem
если нужны еще комментарии, могу дописать...

странно, я в одной функции использовал младшую часть регистра rbx (bl) и забыл его сохранить, ваша утилита это не смогла проверить =(

**Comment by imihajlow** [comment]
Ошибка в `biSign`, например, на числе `biFromInt(-1000000000000ll)`.

**Comment by eugene536** [comment]
исправил, =(

**Comment by imihajlow** [comment]
Ошибка при делении маленького числа (3) на очень большое. Попробуйте разные комбинации знаков.

**Comment by eugene536** [comment]
исправил

**Comment by imihajlow** [comment]
```
test.cpp:7:19: fatal error: gmpxx.h: No such file or directory
```

**Comment by eugene536** [comment]
да я уже перепушил

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
