### ISSUE TITLE
2536/Sholokhov

### ISSUE THREAD

**Issue by aksholokhov** [itmoasm2015/Homework3#32]
Все необходимые операции реализованы. biToString реализован. biDivRem - нет.

**Comment by imihajlow** [comment]
Невыровненный стек при вызове free.

**Comment by aksholokhov** [comment]
Пофиксил.

**Comment by imihajlow** [comment]
2^1024 + (1 - 2^1024) ≠ 1

**Comment by aksholokhov** [comment]
Пофиксил

**Comment by imihajlow** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
hw_biToString.to_end () at asmimpl.asm:833
```

**Comment by aksholokhov** [comment]
Есть ли ошибки в основной части задания, или она проходит тесты и ее можно не перепроверять?

**Comment by imihajlow** [comment]
Тесты на основную часть задания проходит.

**Comment by aksholokhov** [comment]
Соответственно, если я не успеваю дочинить toString, то идет полный бал за основную часть без этого бонуса?

**Comment by imihajlow** [comment]
Ну это уже на ваше усмотрение.

**Comment by aksholokhov** [comment]
Верно ли, что если в biToString передали limit > buffer.size, причем BigInt длиннее, чем limit, то программа имеет полное право упасть в segfault и это корректно?
Если да, то, пожалуйста, проверьте, хватает ли длины вашему буферу, чтобы вместить число, ибо это единственный сегфолт, который я смог найти. А в вашем случае ошибка происходит именно из-за нехватки длины буфера. Если же у вас все в порядке, то был бы очень рад контртесту, который роняет прогу, или хотя бы мыслям о его виде исходя из ваших тестов. Как никак, осталось три часа.

**Comment by imihajlow** [comment]
limit=3 попробуйте.

**Comment by aksholokhov** [comment]
Замечательно выводит первые три символа bi1*bi2^n вплоть до n = 5000. Точно ли хватает размера буфера? Тестер с соответствующим Makefile приложил в коммите. 
![123](https://cloud.githubusercontent.com/assets/6594476/7571817/c42c6ddc-f822-11e4-8e6a-8d3eaeb076cd.JPG)

**Comment by imihajlow** [comment]
Точно хватает. Я использую mprotect(2), чтобы проверять лимит. Обращение к любому адресу за пределами лимита вызывает segfault.
Проверьте, что вы не пишете в память большими регистрами (сразу по 8 байт, например).

**Comment by aksholokhov** [comment]
Перечитал задание. Я правильно понимаю, что при limit = 3 (само число заведомо длиннее) мы должны выводить два первых символа числа и нулевой символ, а не три первых символа числа? Если да, то исправил, прошу ретест.

**Comment by imihajlow** [comment]
Код 7, комментарии 7.

Теперь я вообще не проверяю результат, если лимит меньше нужного числа символов. Проверяю только то, что не должно быть выхода за пределы буфера.

**Comment by aksholokhov** [comment]
Возможно, глупый вопрос, но 7 + 7 - это только за основную часть, насколько я понял. Issue вы закрыли. Это значит, что biToString не зачтен и +5 за него не будет?

UDP. Посмотрел в табличку, все ок. Вопрос снят.
