### ISSUE TITLE
Яковлева Дарья, 2539

### ISSUE THREAD

**Issue by DariaYakovleva** [itmoasm2015/Homework3#34]
2539/Yakovleva
без деления

**Comment by imihajlow** [comment]
Невыровненный стек при вызове malloc.

**Comment by DariaYakovleva** [comment]
Поправлю. А есть какие-нибудь другие ошибки?:)

**Comment by imihajlow** [comment]
У меня тест падает после первой же ошибки, так что не знаю.

**Comment by DariaYakovleva** [comment]
выровняла

**Comment by imihajlow** [comment]
А вот и нет, снова нет.

**Comment by DariaYakovleva** [comment]
а сейчас?

**Comment by imihajlow** [comment]
Нет, сейчас тоже нет. Используйте инструмент из папки fcheck.

**Comment by DariaYakovleva** [comment]
надеюсь, теперь он выровнялся:(

**Comment by imihajlow** [comment]
Ура, стек выровнялся!

biCmp не возвращает ноль, если ему даны два одинаковых отрицательных числа (не один указатель два раза, а два, созданные из одного и того же инта).

**Comment by DariaYakovleva** [comment]
подскажите, пожалуйста, тест.
у меня работает на [-10^5;0], [-10^12;-10^9]

**Comment by imihajlow** [comment]
```
        BigInt bi1 = _biFromInt(2ll);
        BigInt bi2 = _biFromInt(-123ll);
        BigInt bi3 = _biFromInt(-123ll);
        _biAdd(bi1, bi2);
        assert(_biCmp(bi2, bi3) == 0);
```

**Comment by DariaYakovleva** [comment]
исправила

**Comment by imihajlow** [comment]
2 + 2 ≠ 4 (двойки — один и тот же объект, складывается сам с собой).

**Comment by DariaYakovleva** [comment]
исправила

**Comment by imihajlow** [comment]
Пустая строка не должна допускаться функцией biFromString.

**Comment by DariaYakovleva** [comment]
исправила

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
