### ISSUE TITLE
Антон Белый, 2539

### ISSUE THREAD

**Issue by AVBelyy** [itmoasm2015/Homework3#38]
2539/Belyy

Дополнительно к уже сданному заданию реализован перевод в строку за O(n^2).
Реализовано, но пока, к сожалению, не доведено до рабочего состояния длинное деление методом Кнута (TAOCP, Seminumerical algorithms) (методом угадывания разряда) за O(m*(n - m)), где n – размер делимого, m – размер делителя.

Также в виду появления новых операций заметно усложнился тестер.

**Comment by imihajlow** [comment]
Вывод в строку принят.

**Comment by AVBelyy** [comment]
Кажется, я еще не успел закоммитить изменения на момент написания issue. :)
Правда ли, что вывод в строку действительно проверен и засчитан?

**Comment by imihajlow** [comment]
Да, вывод в строку работает.

**Comment by AVBelyy** [comment]
А тестер посмотрите?

**Comment by AVBelyy** [comment]
Ну ладно.
