### ISSUE TITLE
Волхов Михаил 2538

### ISSUE THREAD

**Issue by volhovm** [itmoasm2015/Homework3#40]
subj

**Comment by imihajlow** [comment]
Невыровненный стек при вызове malloc.

**Comment by imihajlow** [comment]
`biCmp` работает неправильно.

**Comment by volhovm** [comment]
fixed

**Comment by imihajlow** [comment]
Невыровненный стек при вызове free.

Такой красивый тестер с зелеными скобочками, а стек не проверяет.

**Comment by volhovm** [comment]
Вроде пофиксил. Внимательность -- не мой конёк, конечно (а очень жаль). 
Fcheck нормально тестит, кстати.

**Comment by imihajlow** [comment]
Неа. При тесте biToString невыровненный стек.

**Comment by volhovm** [comment]
:goberserk: 
Пофиксил вроде бы...

**Comment by volhovm** [comment]
inb4 почему нельзя просто потестить на линухе?

**Comment by imihajlow** [comment]
Я на линуксе и тестирую. Просто в этом задании всё серьезно, конвенция вызова должна быть соблюдена полностью. Впрочем, я всё же не проверяю, насколько хорошо вы обрабатываете те ситуации, когда внешние функции портят те регистры, которые им разрешено портить.

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
