### ISSUE TITLE
Shvedov Denis,2536

### ISSUE THREAD

**Issue by shvedov1995** [itmoasm2015/Homework3#42]
с biToString

**Comment by imihajlow** [comment]
При умножении положительного числа на -1 не получается отрицательное число.

**Comment by shvedov1995** [comment]
Исправил
Ой,только я нашел крупный баг в делении,пока не знаю,как фиксить,так что,сдаю без него

**Comment by imihajlow** [comment]
Код 8, комментарии 7.
