### ISSUE TITLE
Муратов Амир, 2539

### ISSUE THREAD

**Issue by AmirMuratov** [itmoasm2015/Homework3#43]
Не реализовано деление

**Comment by imihajlow** [comment]
Невыровненный стек при вызове malloc. Воспользуйтесь инструментом из папки fcheck.

**Comment by AmirMuratov** [comment]
Исправил выравнивание стека. Прошу прощения за задержку, надеюсь еще не слишком поздно.

**Comment by imihajlow** [comment]
(2^1024-1) - (-1) ≠ 2^1024

**Comment by AmirMuratov** [comment]
Исправил

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
