### ISSUE TITLE
Shovkoplias Grigory, 2539

### ISSUE THREAD

**Issue by gshovkoplyas** [itmoasm2015/Homework3#46]
Не успел написать умножение, зато есть вывод в строку. Надеюсь какой-нибудь эпсилон это получит.

**Comment by imihajlow** [comment]
2 + (-123) ≠ -121

**Comment by gshovkoplyas** [comment]
@imihajlow  Пофиксил, но поздно. Тупая ошибка из-за копипасты(
ровно одна строчка изменилась

**Comment by imihajlow** [comment]
Завтра доделай и сдай с умножением.

**Comment by gshovkoplyas** [comment]
@imihajlow Хорошо, спасибо, большое.

**Comment by gshovkoplyas** [comment]
@imihajlow Закончил

**Comment by imihajlow** [comment]
R12 не сохраняется.

**Comment by gshovkoplyas** [comment]
@imihajlow Ой) Пофиксил)

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
