### ISSUE TITLE
Несколько вопросов

### ISSUE THREAD

**Issue by gerra** [itmoasm2015/Homework3#6]
1. Если у нас число -234, например, то после biToString(a, s, 3) s будет "-2",0 ??
2. Будут ли баллы сниматься за неиспользование векторных расширений? Там не учитываются знаки, а по ссылке, которую вы кидали в прошлый issue, немного геморно :(

**Comment by imihajlow** [comment]
1. Да.
2. Нет. Можно писать совсем без векторных расширений, но если вы придумаете какое-нибудь красивое и быстрое решение, то обязательно получите бонус.
