### ISSUE TITLE
Бережко Герман, 2538

### ISSUE THREAD

**Issue by gerra** [itmoasm2015/Homework3#7]
2538/berezhko

Не реализовано деление.

**Comment by imihajlow** [comment]
Segfault в `biCmp`.

**Comment by gerra** [comment]
А тест не скажете? :)

**Comment by imihajlow** [comment]
Создать два числа с помощью `biFromInt`, создать так же третье число — сумму первых двух, сложить первые два числа с помощью `biAdd`, сравнить результат сложения и третье число.

**Comment by gerra** [comment]
for (int i = 0; i < 10000; i++) {
        int64_t x = genInt();
        int64_t y = genInt();
        BigInt a = biFromInt(x);
        BigInt b = biFromInt(y);
        BigInt c = biFromInt(x+y);
        biAdd(a, b);
        biCmp(a, c);
    }

Вот так запускаю, segfault'а нету :(( не подскажете как можно такие числа найти или тут кроме как внимательного изучения кода ничего не поможет, так как мне просто везет (хотя скорее не везет)?

**Comment by imihajlow** [comment]
Извиняюсь :) У меня был неправильный тест.

**Comment by gerra** [comment]
Ааа, и такое случается ))
То есть сейчас задание на стадии "пока все окей, проверяется"?)

**Comment by imihajlow** [comment]
```
BigInt bi1 = biFromInt(2ll);
BigInt bi2 = biFromInt(-123ll);
BigInt bi3 = biFromInt(-123ll);
biAdd(bi1, bi2);
biSub(bi1, bi2);
assert(biCmp(bi2, bi3) == 0);
```

`biCmp` не возвращает ноль в этом случае.

**Comment by gerra** [comment]
исправил

**Comment by imihajlow** [comment]
Стек перед вызовом внешних функций должен быть выровнен на 16 байт (перед вызовом `calloc` у вас стек не выровнен). Проверьте все вызовы.

**Comment by imihajlow** [comment]
Извиняюсь, при вызове `malloc` невыровнено.

**Comment by gerra** [comment]
Надеюсь, всё исправил. А как можно следить за выравниванием? Вдруг опять в этом ошибка будет, а уже хочется результаты узнать ))

**Comment by imihajlow** [comment]
Теперь `calloc` невыровнен.
Я добавил в репозиторий инструмент для проверки выравнивания и регистров.

**Comment by gerra** [comment]
вот теперь выровнено. возможно, немного костыльно, но просто у меня calloc и free вызывается из многих мест и везде стек выровнен по-разному и так и не смог обойтись просто sub и add

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
