### ISSUE TITLE
Шатров Виктор, 2538

### ISSUE THREAD

**Issue by vi34** [itmoasm2015/Homework3#8]
2538/Shatrov
Не реализовано деление

**Comment by imihajlow** [comment]
R15 надо сохранять (RBX, RBP, R12-R15).

**Comment by vi34** [comment]
Исправлено

**Comment by imihajlow** [comment]
Стек перед вызовом внешних функций должен быть выровнен на 16 байт (перед вызовом `free` у вас стек не выровнен). Проверьте все вызовы.

**Comment by vi34** [comment]
Исправлено

**Comment by imihajlow** [comment]
Код 8, комментарии 5.
