### ISSUE TITLE
Шах Егор, 2538

### ISSUE THREAD

**Issue by sultanko** [itmoasm2015/Homework3#9]
2538/Shah
реализован biToString
реализован biDivRem

**Comment by imihajlow** [comment]
`biAdd` возвращает NULL.

**Comment by imihajlow** [comment]
```
bi1 = biFromInt(0xffffffffll);
bi2 = biFromInt(0xffffffffll);
bi5 = biFromInt(0xffffffffll + 0xffffffffll);
biAdd(bi1, bi2);
assert(biCmp(bi1, bi5) == 0);
```

`biCmp` здесь выдает не ноль.

**Comment by sultanko** [comment]
Исправлено

**Comment by imihajlow** [comment]
`biToString` не сохраняет R15.

**Comment by sultanko** [comment]
Исправлено

**Comment by imihajlow** [comment]
2^1024 + (-(2^1024 - 1)) ≠ 1

**Comment by sultanko** [comment]
Исправлено.

**Comment by sultanko** [comment]
Реализовано деление. Можете перетестировать?

**Comment by imihajlow** [comment]
Стек перед вызовом внешних функций должен быть выровнен на 16 байт (перед вызовом `malloc` у вас стек не выровнен). Проверьте все вызовы.

**Comment by sultanko** [comment]
Скажите, а можно ли это как-то проверять автоматически выравнивание стека или только глазами? Я исправил в одном месте, но не знаю, может еще где-то забыл.(в трех местах). Проверил утилитой.

**Comment by imihajlow** [comment]
Добавил в репозиторий инструмент для проверки выравнивания.

А у вас новая ошибка: деление неправильно работает. Делимое ±(p1 \* p2 + p3), делитель ±p2, где p1, p2 и p3 — простые числа порядка 2^255. Проверка результата через умножение и сложение.

**Comment by sultanko** [comment]
Я не могу воспроизвести тест, генерю числа также(только p1-p3 не факт, что простые) и проверя через biMul, biAdd. И все работает. Также пытался проверить через пару больших простых чисел, все равно работает. У вас можно вывести эти числа? (кстати, а почему вы не выложите тесты также, как и утилиту для проверки регистров, это бы облегчило всем жизнь)

**Comment by imihajlow** [comment]
Делимое `6703903964971298549787012499102923063739682910296196688861780721860882015023660034294811089951732299792782023528860199663493147528504713584320662571322642`,
делитель `57896044618658097711785492504343953926634992332820282019728792003956564819949`.

**Comment by imihajlow** [comment]
Не забудьте все комбинации со знаками.

**Comment by sultanko** [comment]
Исправлено. Как оказалось, это старый баг, еще в сложении. Очень хорошие числа.

**Comment by imihajlow** [comment]
Код 8, комментарии 5.
